In [54]:
import pandas as pd
import numpy as np
import random

In [2]:
df = pd.read_csv("../data/raw/positive_rep_virus_dataset.csv")

In [3]:
df

,taxid,virus_name,sDBM_pos,sDBM,sDBM_sim_gap,ori_seq,ori_align_score,iteration_name,rep_amino_acid_seq
0,59817,Faba bean necrotic yellows virus,"(63, 71)",GAHFEKRRG,33.0,TAGTATTAC,138.5,FBNYY_iter1_V_A,MARQVICWCFTLNNPLSPLSLHDSMKYLVYQTEQGEAGNIHFQGYI...
1,262588,Cardamom bushy dwarf virus,"(63, 71)",GAHLEKRKG,33.1,TATTATTAC,138.2,FBNYY_iter1_V_A,MARYVVCWMFTINNPSSLPVMRDEIKYMVYQVERGQEGTRHVQGYV...
2,1819678,Cucurbit yellow mosaic alphasatellite,"(66, 74)",GTHIEACKG,36.2,GATTTGTAC,129.9,FBNYY_iter1_V_A,MSHSRNWCFTIFNYVLPLFTTLPEWANYLIYQEEECPTTKKRHIQG...
3,1260769,Colecusatellite agerati,"(73, 81)",KPHLEKQRA,22.3,GACTGCTAC,130.0,FBNYY_iter1_V_A,MAAIKGQWWCFTVFFLTATAPDLVPLFENTHVSYACWQEEESPTTK...
4,2169722,Banana bunchy top alphasatellite 2,"(70, 78)",RAHWEKARG,40.3,TAGTATTAC,138.5,FBNYY_iter1_V_A,MSASRWTFTLHYSDATERGKFLATLKEEDVHYAVVGDETAPNTGRK...
...,...,...,...,...,...,...,...,...,...
279,222450,Chayote yellow mosaic virus,"(88, 96)",HPNVQGAKS,37.7,TTATACTAC,132.4,SGC1_iter2_V_R,MAPPKRFQINAKNYFLTYPQCSLTKEEALSQLRSLRTPTNQKYIKV...
280,223332,Tobacco leaf curl Japan virus,"(88, 96)",HPNIQGAKS,37.9,TAATATTAC,139.3,SGC1_iter2_V_R,MAPPKRFQINAKNYFLTYPHCSLTKEEALSQIQALDTITNKLFIRI...
281,486809,Ramie mosaic virus,"(88, 96)",HPNIQGAKS,37.4,TAATATTAC,139.3,SGC1_iter2_V_R,MAPPRRFTINAKNYFLTYPQCPLSKEEALSQLLNLSTPTNKKFIKI...
282,390437,Kudzu mosaic virus,"(88, 96)",HPNIQGAKS,37.0,TTATCCTAC,130.6,SGC1_iter2_V_R,MSRPKGFRVNAKNFFLTYPRCSLSKEAALEQLQNIQTNVNKKFIRV...
283,75574,Jatropha mosaic virus,"(88, 96)",HPNIQGAKS,38.0,CAATTGTAC,132.1,SGC1_iter2_V_R,MPRKGSFSIKAKNYFLTYPQCSLTKEEALSQLQNLNTPINKKFIKI...

In [4]:
# Remove NaN ori
df.dropna(inplace=True) #inplace=True avoids reassignment of dataset

# Drop entries where sDBM confidence < 10
df = df[df['sDBM_sim_gap'] >= 10]

# Drop entries where ori score < 130
df = df[df['ori_align_score'] >= 130]

len(df)

238

In [5]:
negative_df = df.copy()

In [72]:
def shuffle_until_no_match(max_attempts=10000):

    minMatches = np.inf
    best_shuffle = None
    best_shuffle_same_ori_rows = None

    for _ in range(max_attempts):
        negative_df['ori_seq'] = np.random.permutation(negative_df['ori_seq'])

        boolarr = negative_df['ori_seq'].values == df['ori_seq'].values


        if not np.any(boolarr):
            print("Perfect shuffle")
            return

        if boolarr.sum() < minMatches:
            minMatches = boolarr.sum()
            best_shuffle_same_ori_rows = np.where(boolarr)[0]
            best_shuffle = negative_df.copy()

    
    print(best_shuffle_same_ori_rows)


    print("Failed")

    print(minMatches)

    return best_shuffle, best_shuffle_same_ori_rows, minMatches

In [66]:
#for misses, just randomly mutate the ori

In [73]:
best_df, indices, minMatches = shuffle_until_no_match()

[  9  22  31  90 118]
Failed
5

In [74]:
best_df

,taxid,virus_name,sDBM_pos,sDBM,sDBM_sim_gap,ori_seq,ori_align_score,iteration_name,rep_amino_acid_seq
0,59817,Faba bean necrotic yellows virus,"(63, 71)",GAHFEKRRG,33.0,CAGTATTAC,138.5,FBNYY_iter1_V_A,MARQVICWCFTLNNPLSPLSLHDSMKYLVYQTEQGEAGNIHFQGYI...
1,262588,Cardamom bushy dwarf virus,"(63, 71)",GAHLEKRKG,33.1,TAGTATTAC,138.2,FBNYY_iter1_V_A,MARYVVCWMFTINNPSSLPVMRDEIKYMVYQVERGQEGTRHVQGYV...
3,1260769,Colecusatellite agerati,"(73, 81)",KPHLEKQRA,22.3,TATTTTTAC,130.0,FBNYY_iter1_V_A,MAAIKGQWWCFTVFFLTATAPDLVPLFENTHVSYACWQEEESPTTK...
4,2169722,Banana bunchy top alphasatellite 2,"(70, 78)",RAHWEKARG,40.3,TATTATTAC,138.5,FBNYY_iter1_V_A,MSASRWTFTLHYSDATERGKFLATLKEEDVHYAVVGDETAPNTGRK...
6,1685737,Lake Sarah-associated circular virus-11,"(74, 82)",RAHFECAKG,40.2,TAGTATTAC,137.7,FBNYY_iter1_V_A,MAPRGNAAKRWTFTINNWTLADYDKVLEFTTKFEPVFLICGKERGE...
...,...,...,...,...,...,...,...,...,...
279,222450,Chayote yellow mosaic virus,"(88, 96)",HPNVQGAKS,37.7,GAGTCATAC,132.4,SGC1_iter2_V_R,MAPPKRFQINAKNYFLTYPQCSLTKEEALSQLRSLRTPTNQKYIKV...
280,223332,Tobacco leaf curl Japan virus,"(88, 96)",HPNIQGAKS,37.9,TAGTATTAC,139.3,SGC1_iter2_V_R,MAPPKRFQINAKNYFLTYPHCSLTKEEALSQIQALDTITNKLFIRI...
281,486809,Ramie mosaic virus,"(88, 96)",HPNIQGAKS,37.4,TAGTATTAC,139.3,SGC1_iter2_V_R,MAPPRRFTINAKNYFLTYPQCPLSKEEALSQLLNLSTPTNKKFIKI...
282,390437,Kudzu mosaic virus,"(88, 96)",HPNIQGAKS,37.0,CATTATTAC,130.6,SGC1_iter2_V_R,MSRPKGFRVNAKNFFLTYPRCSLSKEAALEQLQNIQTNVNKKFIRV...
283,75574,Jatropha mosaic virus,"(88, 96)",HPNIQGAKS,38.0,TTTTTTTAC,132.1,SGC1_iter2_V_R,MPRKGSFSIKAKNYFLTYPQCSLTKEEALSQLQNLNTPINKKFIKI...

In [75]:
def mutate_ori_dataset(df, rows):

    bases = ['A', 'C', 'T', 'G']

    for row in rows:

        random_pos =random.randint(0, 6)
        random_base = random.choice(bases)

        same_ori = df.iat[row.item(), 5] 
        mutated_ori = same_ori[:random_pos] + random_base + same_ori[random_pos + 1:]
        print(same_ori)
        print(mutated_ori)

        df.iat[row.item(), 5] = mutated_ori

In [84]:
mutate_ori_dataset(best_df,indices)

TACGCTTAC
TACGATTAC
CACTGATAC
CACTGAGAC
TCATGCCAC
CCATGCCAC
ACATAAAAC
ACATAAAAC
GAGTGGAAC
GTGTGGAAC

In [8]:
best_df2 = shuffle_until_no_match()

Failed
5

In [51]:
# Print entire dataset!

print(len(df))
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

238

,taxid,virus_name,sDBM_pos,sDBM,sDBM_sim_gap,ori_seq,ori_align_score,iteration_name,rep_amino_acid_seq
0,59817,Faba bean necrotic yellows virus,"(63, 71)",GAHFEKRRG,33.0,TAGTATTAC,138.5,FBNYY_iter1_V_A,MARQVICWCFTLNNPLSPLSLHDSMKYLVYQTEQGEAGNIHFQGYI...
1,262588,Cardamom bushy dwarf virus,"(63, 71)",GAHLEKRKG,33.1,TATTATTAC,138.2,FBNYY_iter1_V_A,MARYVVCWMFTINNPSSLPVMRDEIKYMVYQVERGQEGTRHVQGYV...
3,1260769,Colecusatellite agerati,"(73, 81)",KPHLEKQRA,22.3,GACTGCTAC,130.0,FBNYY_iter1_V_A,MAAIKGQWWCFTVFFLTATAPDLVPLFENTHVSYACWQEEESPTTK...
4,2169722,Banana bunchy top alphasatellite 2,"(70, 78)",RAHWEKARG,40.3,TAGTATTAC,138.5,FBNYY_iter1_V_A,MSASRWTFTLHYSDATERGKFLATLKEEDVHYAVVGDETAPNTGRK...
6,1685737,Lake Sarah-associated circular virus-11,"(74, 82)",RAHFECAKG,40.2,CAGTATTAC,137.7,FBNYY_iter1_V_A,MAPRGNAAKRWTFTINNWTLADYDKVLEFTTKFEPVFLICGKERGE...
7,2293298,Pimoid spider associated circular virus 2,"(66, 74)",SAHWERTKG,36.8,TAGTATTAC,138.5,FBNYY_iter1_V_A,MSCKNWCFTWNNPDLGYEALLELLSSKSSYCIFQKEQGANGTVHFQ...
8,3429808,Hudisavirus jaqis,"(73, 81)",RAHWEKTRG,37.0,GAGTATTAC,136.3,FBNYY_iter1_V_A,MSAQEGAAKRWCFTINNPTDDDKFWENSEQQEHLEYLIIQEEIGEN...
9,2800901,Marmot associated feces virus 6,"(68, 76)",KIHWEPRKG,29.4,AATTATTAC,137.5,FBNYY_iter1_V_A,MSRNRNWVFTFNNPYDIEIQMLDKILTSQADYAIYGEEVGENGTPH...
10,1234878,Dragonfly cyclicusvirus,"(67, 75)",RYHIEMRRG,37.5,TAGTATTAC,138.5,FBNYY_iter1_V_A,MGSPAIGWCFTLNNYTEIDEQVLQALDVKYLVYGHEVGEGGTPHLQ...
11,2676049,Penguin circovirus,"(73, 81)",RAHWEKARG,42.2,TAGTATTAC,138.5,FBNYY_iter1_V_A,MAPVRAAGARRWCLTLNNPTDEEVQAAKRLEPNTYHYAIIGREVGE...
12,2293292,Golden silk orbweaver associated circular virus 1,"(64, 72)",GAHFERARG,39.7,CAGTATTAC,137.7,FBNYY_iter1_V_A,MSKCKRWLFTSYNVVSEPFYDEKIHEYLCFGRETCPSTNRRHLQGY...
14,2817738,Wolvfec circovius,"(73, 81)",RAHLEAAKG,38.6,GAGTATTAC,136.3,FBNYY_iter1_V_A,MGREAPKRRWCFTINNWTGEELESIKQSTKDIAKYLCIGKEVGKNG...
15,2170111,Gorilla associated porprismacovirus 1,"(67, 75)",KAHIEEASD,22.5,TAGTGTTAC,135.9,FBNYY_iter1_V_A,MTQTWMLTVPRRKTEKEWMGIYKWLRDNDVHKWTVAMETGNNGYDH...
16,2683340,Milk vetch chlorotic dwarf virus,"(63, 71)",GAHFEKRRG,31.6,GAGTCATAC,130.2,FBNYY_iter1_V_A,MARQVICWCFTLNNPLSHLSLHESMKYLVYQQEQGESGNIHFQGYV...
17,2169829,Whitefly associated Puerto Rico alphasatellite 1,"(66, 74)",GVHLEQARG,39.7,TAGTATTAC,138.5,FBNYY_iter1_V_A,MGKSRNYCFTLFSYVLPLFSSLPEWANYLVFQEEESPSTGRKHIQG...
19,2293279,False black widow spider associated circular v...,"(69, 77)",RAHWEMRRG,29.6,TAGTATTAC,138.5,FBNYY_iter1_V_A,MSRGRNWLFTENNPTLNPNDFLESAKLWDHVRYIIFQQETGEGGTS...
20,3017836,Army ant associated cyclovirus 9,"(73, 81)",KAHIERAAA,37.7,TAGTATTAC,138.5,FBNYY_iter2_V_A,MALNNTLRRFCFTIPNYTDDDVRRVQEFAKNESKYFVYGREICPRT...
21,1234880,Dragonfly cyclovirus 2,"(119, 127)",TAHIEKANG,42.2,TAGTATTAC,138.5,FBNYY_iter2_V_A,MGCAGATRAVGITRPVARSARSLSRIERRLRSTLPGSRSRSIRYTF...
23,1796013,Pacific flying fox faeces associated circular ...,"(71, 79)",KPHVEVAKG,38.8,CAGTATTAC,137.7,FBNYY_iter2_V_A,MGSQLTQRSRNFCFTLNNYTESDTEAVKAIDCKYMVVGFEVGEKGT...
24,3429998,Janusivirus portis,"(76, 84)",SAHIEPARG,40.5,TAGTATTAC,138.5,FBNYY_iter2_V_A,MSANINRRRQSKSWCFTYNNYTDADYTRICESLDRLCSYYCIGKEV...
25,2873951,WigFec circovirus 1,"(71, 79)",RAWISPARG,35.4,TATTATTAC,138.2,FBNYY_iter2_V_A,MSYARKRYVFTINNPTFEDYCAVVEFCTTSNCCYAVVGEEVGEKGT...
26,1843771,Llama faeces associated circular DNA virus-1,"(80, 88)",RCHIESSRG,44.0,TAGTATTAC,138.5,FBNYY_iter2_V_A,MPSNPQFFHFCFTLNNYVEEVLDDVEEEDVPRISAFCEEEGKYWII...
27,1959744,European catfish circovirus,"(98, 106)",RCHIEKARG,48.9,TAGTATTAC,138.5,FBNYY_iter2_V_A,MPKYQKKSPGKENRSPVQRPKQARPPKKEAPHKRYVFTLNNYTTEE...
28,2586183,Blackfly DNA Virus 3,"(75, 83)",RLHLEVARG,42.7,CAGTATTAC,137.7,FBNYY_iter2_V_A,MPRTQNGSSAKNWCFTLNNYTEEEQFTLEAALSASSDYSIVGREVG...
29,257468,Muscovy duck circovirus,"(75, 83)",RAWLSRARG,34.8,AAGTATTAC,137.8,FBNYY_iter2_V_A,MAKSGNYSYKRWVFTINNPTFEDYVHVLEFSTLDNCKFAIVGEEKG...
30,3431834,Porprismacovirus canid3,"(64, 72)",TAHVEQSTA,17.7,GATTATTAC,136.0,PVC3_iter1_V_A,MDTYVMTIPRTVPKRALKVMIDVNDCKKWIIGKETGKNGYEHWQVR...
31,2170117,Porcine associated porprismacovirus 10,"(85, 93)",YAHIEKSDV,18.3,TAGTGTTAC,135.9,PVC3_iter1_V_A,MQTWVLTIPRRTEIQVPTWLWLAWEPVTIVSVCSKKLLNYILEQSD...
32,2293284,Fly associated circular virus 4,"(83, 91)",CAHIEESTS,19.8,TAGTGTTAC,135.9,PVC3_iter1_V_A,MVKVYLLTVPLVHRIQFDSPLYRWRHSSSYSTKRAIRILIESLDCK...
33,2720966,Chicken smacovirus mg7_67,"(64, 72)",TAHVEEAQD,21.7,GAGTAGTAC,132.3,PVC3_iter1_V_A,MKTYMLTIPRSVPKKAIRIMIEVNDCKRWIVAKETGHGGYDHWQIR...
36,1592122,Odonata-associated circular virus 21,"(116, 124)",GWHVERCIS,13.1,TAGTCTTAC,135.9,PVC3_iter1_V_A,MKKCEACEERPANYGYVKWINCIDGIDRYWFGYICDECYHKFEEEW...
37,2169936,Human associated huchismacovirus 3,"(68, 76)",FGHVSPTHV,11.0,CAGTATTAC,137.7,PVC3_iter1_V_A,MPSPKWYDITASKEKLPRSILEKWLNERCERWAYGNEVGEGGYEHY...
39,2817834,Delphin virus 1,"(74, 82)",KAHWEAARG,36.9,TAGTATTAC,138.5,PVC3_iter1_V_A,MAKKQDTLKRMWIFTLNNYSEENVKHIKQYFNDDRCTYAIVGKEIG...
41,2213168,Papio cynocephalus associated smacovirus,"(69, 77)",GCHWTPTKV,15.2,TAGTATTAC,138.5,PVC3_iter1_V_A,MTAPTWWDCTVPNNEKHPEIQMREILDKTTERYAYGREIGGETGYQ...
42,1436892,Pea yellow stunt virus,"(63, 71)",GAHFEKRRG,32.9,TTTTATTAC,133.9,PVC3_iter1_V_A,MSRQVICWCFTLNNPLSPLSLHESMKYLVYQREQGESGNIHFQGYI...
43,1778561,Ctenophore-associated circular virus 4,"(85, 93)",GWHLEVARN,22.6,TAGTATTAC,138.5,PVC3_iter1_V_A,MTEPTQQDTAGNSGGNTKGKRRCFAFTWNNYPEEHFKLFDTVAQLS...
44,2219142,Alces alces faeces associated smacovirus MP78,"(148, 156)",TAHIEEATE,21.0,TAGTATTAC,138.5,PVC3_iter1_V_A,MQRTNKNRSRQVQDQSAGIISTFSCDNIYVHNAFCKTYAYHTFLSL...
46,2170112,Howler monkey associated porprismacovirus 1,"(78, 86)",TASIRKAEV,10.0,TAGTGTTAC,135.9,PVC3_iter1_V_A,MSTTASRQWSTKMSQMYMLTIPRDKVSKRELRIMLDKNDCKKWIIG...
47,2592415,Lynx rufus smacovirus 2,"(70, 78)",RAHVEKASD,22.8,TAGTGTTAC,135.9,PVC3_iter1_V_A,MTENFMITAPRDESKGYKEWNAWIKVMYACDAKKWVIAAEVGRGGY...
49,2571082,Human lung-associated vientovirus FB,"(83, 91)",MPHVGRIQN,19.4,AATTATTAC,137.5,HLV_iter1_V_A,MTLRLQNKNLYLTYLDTEERIFSELILITELAERLDKYGVKYAIAC...
50,2293273,Arboreal ant associated circular virus 1,"(71, 79)",AVHIEKAMG,42.0,TAGTATTAC,138.5,HLV_iter1_V_A,MNATVRRFVFTLNNYSEEDVTKIKLFINTYCKYGIFGKELAPTTNT...
51,2914454,Chifec virus UA13_1727,"(72, 80)",SIHLEKANG,41.4,TAGTATTAC,138.5,HLV_iter1_V_A,MANGTVRRFCFTLNNYSDEDVEKCKSFITTKCKYGIFGKEVAPTSG...
52,742923,Cyclovirus NG14,"(80, 88)",RIHIEKAAG,44.3,TCGTATTAC,133.7,HLV_iter1_V_A,MALADVRGMANSTVRRFCFTWNNYSELEYVLCCEFIKKYCCYGIVG...
53,3052133,Circovirus siksparnis,"(78, 86)",RCHFEHAKG,47.4,TAGTATTAC,138.5,HLV_iter1_V_A,MVNPKKSGQPPHKRWVFTLNNPTAEEEQKIMSLDMDMFEYFVCGRE...
54,2682467,Werosea circovirus,"(80, 88)",RAHLEQAMG,41.9,TAGTATTAC,138.5,HLV_iter1_V_A,MATPAKQRKRDNPVKRWCLTLNNPTDEEKAALTAKLTEDNCEYAII...
55,2951261,Calfel virus LSF45_cir359,"(81, 89)",RAHVEPARG,42.2,CAGTATTAC,137.7,HLV_iter1_V_A,MRRSAACTGGRGAPAYRWCFTVNNWTEEEHGQILSTCESSVKYLII...
56,2294094,Paguma larvata circovirus,"(73, 81)",RAHLEAARG,38.3,TATTGTTAC,135.6,HLV_iter1_V_A,MAERVPPVRWCFTLNNWTQEEWDSITQVLGPTVKYLCVGKEVGKEG...
57,2911954,Eumops bonariensis associated circovirus 1,"(100, 108)",RAHAEPARG,40.1,TAGTATTAC,138.5,HLV_iter1_V_A,MGSRGTQSVCSGLSTRPFTKLCVGFAGTPRGNPACRWCFTLNNWTE...
59,3431561,Pelorivirus melia,"(81, 89)",RAHFEIMQG,33.1,TCTTCTTAC,130.8,HLV_iter2_V_A,MFNLAQNFSMATKTSRPHARRYCFTLNNYTRDEEEAIKQINCEWLV...
60,2714167,Northern red-backed vole stool-associated circ...,"(71, 79)",EAHWEPARG,36.1,TAATTCTAC,132.8,HLV_iter2_V_A,MTQARGWCGTLNSVPADFDGTEFFKQLDGKIKYAVGQVEVGKETAR...
61,1530454,Feline cyclovirus,"(67, 75)",EIHIEIARG,31.3,TATTACTAC,136.2,HLV_iter2_V_A,MMMTIKNYKTTHEIGANTPLLEKKTLQQQEHHTFKDTCKYNINNLF...
62,2714164,Northern red-backed vole stool-associated circ...,"(71, 79)",HAHWETARG,36.2,TAGTATTAC,138.5,HLV_iter2_V_A,MPSGAKCWCGTLQLDDITFDGQLYLQNLLDSKIITYGVGQVEQGSH...
63,85708,Porcine circovirus 2,"(80, 88)",RCHIEKAKG,51.4,CATTTCTAC,133.3,PCV_iter1_V_A,MPSKKNGRSGPQPHKRWVFTLNNPSEDERKKIRELPISLFDYFIVG...
64,2834422,Equine circovirus 1,"(77, 85)",RCHIEKAKG,51.0,AAGTATTAC,137.8,PCV_iter1_V_A,MVKRRSGPQPNKRWVFTLNNPTPEEEAKIADLDGNLFDYLIVGREG...
65,1329650,Bat circovirus,"(85, 93)",RAHCEKARG,42.7,TAGTATTAC,138.5,PCV_iter1_V_A,MAEAEGPAGGKTRRPREAPAARWCFTLNNPTEEEKEQIKSIEEAKV...
66,1194757,Canine circovirus,"(83, 91)",RGHFEPARG,39.4,TAGTATTAC,138.5,PCV_iter1_V_A,MAQAQVDQRGRDSRRGNPVRRWCFTINNPTPEEEDAVKNLAPDAKY...
67,3052126,Circovirus kiore,"(81, 89)",RCHLEPARG,42.9,TAGTATTAC,138.5,PCV_iter1_V_A,MAQQQLVQQRLVKQGARGRWCFTINNYSAHEEDAVKALAPLAKYLI...
68,2771381,Sonfela circovirus 2,"(68, 76)",RAHFEKAKG,43.6,TAGTATTAC,138.5,PCV_iter1_V_A,MPASYRWAFTLNNPTDEEKSLVRSWEPTQVKYLIAGEEVGDKGTPH...
69,2598785,Beaked whale circovirus,"(68, 76)",RAHFEKAKG,42.2,TAGTATTAC,138.5,PCV_iter1_V_A,MSALNRRWCFTVNNPTEADEEAVKSLTEKSKYLICGREKGESGTPH...
70,2879287,Mongoose-associated circovirus,"(82, 90)",RAHVEVARG,41.3,CAGTATTAC,137.7,PCV_iter1_V_A,MSTARAGTYKKRSAAAYRWCFTVNNWTEEEYGLITSIPRSSVKYLI...
71,3025750,Human circovirus 1,"(73, 81)",RAHLEAAKG,38.7,CAGTATTAC,137.7,PCV_iter1_V_A,MQRESPVARWCFTINNWTQEELDCLLQCGKEKAKYLCIGREVGSGG...
72,2929287,Dipodfec virus UA23Rod_1805,"(69, 77)",RCHIEPAKG,44.7,TAGTATTAC,138.5,PCV_iter1_V_A,MQRKCYVFTLNNYEDGDFDDLRNRLSEVCEYAIVGKEVAPETGTRH...
73,1234879,Dragonfly associated cyclovirus 1,"(71, 79)",SIHIEKANG,41.2,TAGTATTAC,138.5,PCV_iter1_V_A,MNITIRRFVFTWNNYTPSDFETCITFLDNFCKYGIIGKEKCPTTQT...
74,3017833,Army ant associated cyclovirus 5,"(72, 80)",RIHIEKANG,44.2,TAGTATTAC,138.5,PCV_iter1_V_A,MANSTVRKFVFTLNNYTDEECIKTKSFIRQYCKYGIFGKELAPNTG...
75,2050587,Bat faeces associated cyclovirus 4,"(72, 80)",RIHLEKANG,43.3,TATTTCTAC,134.1,PCV_iter1_V_A,MANSTVRRFCFTWNNPTELDFALCSEFIKKYCKYGIVGKEIAPTTG...
76,2771212,Caesalpinia ferrea associated virus,"(69, 77)",GSHIEAAKG,40.6,TAGTATTAC,138.5,PCV_iter1_V_A,MSRSRAWCITVNNYSENDEARCREVGRRCVYAIFGREEAPTTNTRH...
77,2714177,Werosea cyclovirus,"(73, 81)",RVHIELAKG,43.3,TAGTATTAC,138.5,PCV_iter1_V_A,MTENAFVRRFCFTLPNWTEDDYAIIKAFIIQYGKYGIIGKEHCPTT...
78,1685754,Lake Sarah-associated circular virus-27,"(71, 79)",RVHLEAAKG,38.1,AAGTATTAC,137.8,PCV_iter1_V_A,MDPQGRGWCFTLNNPDDLDVLLPQSWDPDSYDYLVYHLEMGAEGTA...
79,1692251,Hermit crab associated circular genome,"(64, 72)",RAHWEVAKG,38.7,CAGTATTAC,137.7,PCV_iter1_V_A,MISKRWCYTLNNYSEDDVVTMKAVPTTYHVLGKEVGTNGTPHIQGF...
80,1592124,Odonata-associated circular virus-4,"(66, 74)",RAHIEAARG,39.3,TAGTATTAC,138.5,PCV_iter1_V_A,MPSTITYIFTINNPTEDDTDKLQLAPGITSIAYQYERGETGTRHIQ...
81,2863967,Red panda feces-associated circular DNA virus 14,"(75, 83)",RAHFEIARG,39.7,CAGTATTAC,137.7,PCV_iter1_V_A,MPRAPQSSQAKRWLFTLNNFSEVERDGLLERLRELSSYFIVGRERG...
82,2714166,Northern red-backed vole stool-associated circ...,"(74, 82)",SAHWEPARG,35.3,TAGTATTAC,138.5,PCV_iter1_V_A,MVNGSRNWCGTLQLEDETYDAETWFQKLLNDGLVKFVIGQIERGHE...
83,1380894,Farfantepenaeus duorarum circovirus,"(72, 80)",GAHCEAAKG,31.8,ACGTTTTAC,130.9,PCV_iter1_V_A,MSGSRRWCFTVFNYNHATVDDFIRAERHDCVRYVVWQCEKCPTSGR...
84,2766565,Giardia-associated CRESS DNA virus 1,"(78, 86)",RSHWEPMYG,34.5,TAGTATTAC,138.5,PCV_iter1_V_A,MPRTPVVQVRNWIGTLNGIDASFDAEGYLRTMVERGLAKYAVGQLE...
86,3431088,Nervillivirus flovetense,"(68, 76)",SADIAIRRG,24.4,AATTATTAC,137.5,PCV_iter1_V_A,MSRGPNWCFTINNWTVEDKQKLDLLECGYVLYGEEVAPTTGTPHLQ...
87,2929266,Sigmofec virus UA08Rod_20100,"(70, 78)",KTHWEPARG,32.9,TAGTATTAC,138.5,PCV_iter1_V_A,MANRSSNWCGTKQLDSEFDAETWLRQLVEQNKAKFVVGQVEQGSHL...
88,2109373,Chicken stool associated circular virus 1,"(93, 101)",RAHWEKTRG,37.8,GAGTATTAC,136.3,PCV_iter1_V_A,MRSNFVISNSVANFRARRDIEMPQETQVKRWCFTINNPTERDRFWE...
90,3432171,Robaratusivirus semberis,"(76, 84)",SAHLEPAKG,37.3,AATTATTAC,137.5,PCV_iter2_V_A,MSSGTNRPVEKEANVRAWCLTINNYTIENVEDLKKLKYLYLIIGNE...
91,2929258,Myodefec virus RodL3_773,"(71, 79)",EAHWEAAKG,34.7,TAGTATTAC,138.5,PCV_iter2_V_A,MTQARCWCGTLNSLPDNFDAEAWIKEKAEKCKFIVGQLEMGHETEH...
92,3433149,Vehemenivirus recresis,"(64, 72)",RAALFRRKG,27.0,GACTAATAC,131.1,PCV_iter2_V_A,MARHFCFTLNNYSFAELIVIESTKCEYIVCGAEICPTTGTRHIQGY...
93,3432919,Torentivirus zocris,"(89, 97)",PGHWEACKG,26.5,CAGTACTAC,135.7,PCV_iter2_V_A,MPASNATKSRKWCFTMFFDIDKMGPRGPEAKYFEDWECEYLYVGLE...
94,2929248,Dipodfec virus UA06Rod_119,"(69, 77)",KTHWEQAKG,37.2,TAGTATTAC,138.5,PCV_iter2_V_A,MSGQGKAWCGTLQLEGDFDGERYLREMVEQGKAKFAVGQIEQGSHL...
95,3433292,Volantivirus zuncris,"(56, 64)",NAHVEVCKG,35.1,TAGTATTAC,138.5,PCV_iter2_V_A,MFVRVRLNCLLTIVFVLFIAPFVERCPTTGKLHCQAYVRYTNQVAL...
96,2016458,Giant panda circovirus 3,"(68, 76)",GVHLERRNG,29.8,TTTTTTTAC,131.8,PCV_iter2_V_A,MPANENTPGKYWCFTSYHNDCPVFDAGTMQYLVYGGEICPRTERRH...
97,2293295,Longjawed orbweaver circular virus 2,"(69, 77)",AAHWEVMKG,31.0,CAGTATTAC,137.7,PCV_iter2_V_A,MSQVKKWTLTINNPGLEDHLTLWAKDVKNYGFQYEKVNTYHLQGWI...
98,1778558,Ctenophore-associated circular virus 1,"(79, 87)",RAHFEKMAG,37.3,TAGTATTAC,138.5,PCV_iter2_V_A,MATSETSETSGGPPPSGTFRAICFTEFGDPPDWDVVQHKLRFMAYG...
99,1454023,Dragonfly larvae associated circular virus-2,"(66, 74)",AAHAELSRS,26.2,TAGTATTAC,138.5,PCV_iter2_V_A,MARRQGIFWLLTIPRHEFVPYLPPGCVWIRGQLEEGGEDGYLHWQV...
100,1454024,Dragonfly larvae associated circular virus-3,"(68, 76)",GCHLEAAMG,40.6,AAGTATTAC,137.8,PCV_iter2_V_A,MANRRSRGWCFTLNNYTPEHEALLAAVPCAYMIFGREVGANGTPHL...
101,3431128,Ninurtavirus momolo,"(91, 99)",ACHAELSRS,27.8,GAATACTAC,132.7,PCV_iter2_V_A,MSQFSSPNSGSVATVESRSLATNQRGARRQGIFWLLTVPHHDFTPF...
102,2282643,Holcus lanatus-associated virus,"(69, 77)",SAHWEPRRG,32.3,CAGTATTAC,137.7,PCV_iter2_V_A,MPRQKSPAHDWCFTINNPRRRDHQRVQDWQYNYLIYQLEVGDQGTP...
104,2766563,Entamoeba-associated CRESS DNA virus 3,"(70, 78)",TADIERAKG,29.7,TAATATTAC,136.9,EAV3_iter1_V_A,MSRARGWFLTENRNIEDSRSALSKICDEGGVRYAVMAKERAPTTGH...
105,1592114,Odonata-associated circular virus-14,"(69, 77)",RADIEIVKG,34.5,TAATATTAC,136.9,EAV3_iter1_V_A,MSQSQQSRRWFITINNYTSADIDALREIECNYIVACTEIAPTTGTP...
106,2293305,Spinybacked orbweaver circular virus 1,"(64, 72)",GAHFEAAKG,38.9,CAGTATTAC,137.7,EAV3_iter1_V_A,MSRCHGWTFTVFALEPEPVFEPNLHEYLIFGRETCPTTGRSHLQGY...
107,2956631,Valinorvirus eriador,"(68, 76)",RIHWETRRG,28.8,TAGTATTAC,138.5,EAV3_iter1_V_A,MIPARAPRSRSWLGCLNNYTAAELEQLRTHECRYMALGFHVGHQSH...
108,1592087,Sewage-associated circular DNA virus-20,"(70, 78)",SAHFETKRG,31.5,CTTTCTTAC,130.5,EAV3_iter1_V_A,MARSRNYVFTVNNYDDEDEHQCWAMPWEVKDCKYICVGKEIGESGT...
109,2282645,Panicum ecklonii-associated virus,"(67, 75)",TAHWEIKRG,31.6,TAGTGTTAC,135.9,EAV3_iter1_V_A,MTKQGSLAKHWVFTSFADEVVFFSNVDVQYCIFGNEQCPKTGRWHK...
110,2829140,Raccoon dog stool-Circo-like_virus,"(87, 95)",NAHLEQAMG,37.0,TAGTATTAC,138.5,EAV3_iter1_V_A,MAGCQVAYDKFTFNMSRTAYARARRWCFTINNPTEDCINDYRNRTT...
111,1796015,Pacific flying fox faeces associated circular ...,"(84, 92)",SAHFERMRG,35.9,TAGTATTAC,138.5,EAV3_iter1_V_A,MSRDKVDLAPSRGFSKYWCFTAFASDFEKFTEIISDERVFSNSDLS...
112,2057942,Pleurochrysis carterae circular virus,"(82, 90)",KCWARPAKT,18.7,TACTATTAC,136.8,EAV3_iter1_V_A,MDNTLEMQAFAHASDTQTKKFRNFVFTKNNYSQEDLDDLDSMEIKY...
113,400121,Gull circovirus,"(89, 97)",RAHFEKARG,42.0,AAGTTCTAC,133.7,EAV3_iter1_V_A,MRRRPRSGRYLRSIMAARRDSGARRWCFTLNNYTPEEEETARNLIH...
114,1506568,Cyclovirus ZM36a,"(73, 81)",RAHIERAKG,44.6,TAGTATTAC,138.5,EAV3_iter1_V_A,MANNSTVRRFCWTLNNYTEDDVDVLQKDLAELCKFAIFGREICPTT...
115,2585037,Capybara virus 10_cap1_55,"(69, 77)",RAHFEVARG,41.9,CAGTATTAC,137.7,EAV3_iter1_V_A,MSRASNWCFTLNNYTEDEYAQVCQALREECKYFIVGRERGAEGTNH...
116,2779356,Gallibacter intestinalis,"(72, 80)",IAHIERARG,37.8,CAGTATTAC,137.7,EAV3_iter1_V_A,MDPQGKKWQITINNPSKAGLNRDAIEEIIKGFSYQYVCMADEIGDS...
117,2886401,robinz virus RP_620,"(70, 78)",SAYITPSHG,37.1,TAATATTAC,136.9,EAV3_iter1_V_A,MTQRIKRVCFTLNNYTLEDEQRIQDGSRDFEYAIYGREIAPTTGTR...
119,40518,Ruminococcus bromii,"(75, 83)",IAHIDKANG,35.4,GAGTATTAC,136.3,EAV3_iter1_V_A,MGSTNLQSRKWLLTVNNPLDYGLNHAEIKNILHLFNPDYFCLVDEI...
120,400122,Finch circovirus,"(74, 82)",RAHFERARG,40.8,AAATGCTAC,131.6,EAV3_iter1_V_A,MPKQARESPCKRWCFTLNNPTEEEIERVKNLSPSEYHYAIVGKEKG...
121,2929252,Dipodfec virus UA04Rod_5913,"(72, 80)",SIHIEKANG,41.8,TAGTATTAC,138.5,EAV3_iter2_V_A,MANSTLRRFVFTWNNYSDSDLIKCKDFITNKCKYGIFGEEVAPTTG...
122,2736692,Ursus americanus circovirus,"(62, 70)",RAHLEAARG,15.7,CTCTATTAC,131.7,EAV3_iter2_V_A,MLDLLQWCFTVNNWTPEEWDSITQLLGPTVKYLCVGKEVGRDGTPH...
123,2929265,Sigmofec virus UA08Rod_19468,"(80, 88)",RAHWEPMRG,33.3,TAGTATTAC,138.5,EAV3_iter2_V_A,MQSTYNGKNWCGTVNNFEDSGIEPDGPRAWLERLVRSGICTFAVGQ...
124,2204155,Chaetoceros tenuissimus DNA virus SS12-43V,"(136, 144)",RVNIRVPKR,11.7,TACTACTAC,134.8,CTS_iter1_V_A,MLTSSHKNKMSQEASIPTTLDLSDELSRVSGLDSAIEEGSLVCYEV...
127,1843767,Deer faeces associated circular DNA virus 1,"(64, 72)",SAHIEYTKN,25.3,TATTCTTAC,135.6,CTS_iter1_V_A,MRSRTYCYTSFKESEPFVDINQIVFQIHQLEICETTGRPHWQGIVA...
128,1844928,Avian-like circovirus,"(73, 81)",RAHWEKARG,40.2,AAGTTATAC,132.2,CTS_iter1_V_A,MPPVRAAPAKRWCFTLNNPTDEEVQKIKDMNPSEYHYAIVGKERGE...
129,1618236,Avon-Heathcote Estuary associated circular vir...,"(66, 74)",RGHWEQRLG,29.8,TAGTATTAC,138.5,CTS_iter1_V_A,MTCRNWCLTLNNFTPEEEEVLKEEKPWIKFVVYQVEMGESGTPHLQ...
130,1642515,Zebra finch circovirus,"(74, 82)",RAHFEIARG,39.4,AAATACTAC,134.2,CTS_iter1_V_A,MPKQARSSPCKRWVFTLNNPTEQEVESVKSLPPSEYHYAIVGKEKG...
133,1346815,Circo-like virus-Brazil hs1,"(74, 82)",GVHLERRMG,31.6,TAATATTAC,136.9,CTS_iter1_V_A,MSYRFWCFTEYEDEKVQNYEEWFNRLFNSEAGIDYICGQRERCPNT...
134,2560714,Rodent associated cyclovirus 1,"(81, 89)",RVHIELARG,34.8,TATTTCTAC,134.1,CTS_iter2_V_A,MQRHVKRLCFTLHDYTESEYNGIINVFKTKCTYLIIGKEICPTTQR...
135,3431138,Ninurtavirus rhiphus,"(69, 77)",TAHAELTRS,24.6,TAGTATTAC,138.5,CTS_iter2_V_A,MERRTQRRQGIFWILTIKHAEFTPYLPPGCAWIRGQLELGESNSFL...
136,2951259,Calfel virus LSF31_cyc420,"(77, 85)",SAHIEYAHG,40.1,CAGTGTTAC,135.1,CTS_iter2_V_A,MAESSTPNYSVRKFVFTHFNYTNEDISRLKAWMEDNCKYAIFGEEI...
137,3038664,Banfec circovirus 2,"(81, 89)",RGHFEPARG,38.9,TAGTATTAC,138.5,CTS_iter2_V_A,MAQAAVDEQKNRRHHPVRRWCFTINNYTAAEEEAVRGLAADAKYLI...
139,2720907,Chicken virus mg5_2876,"(88, 96)",NAHIEVCRG,31.0,TAGTATTAC,138.5,CVM_iter1_V_A,METVENGNTSLGNTKARDVSFGGKARAYQLTLNEVERYDELKDYLT...
140,2800899,Marmot associated feces virus 4,"(88, 96)",NAHVEICRG,30.6,AATTATTAC,137.5,CVM_iter1_V_A,MTTEVMDTPDTGNTICVGSRIFRARAFQLTLNETKWYESLKSEFLK...
141,2929260,Peromfec virus RodF8_96,"(79, 87)",NCHVEKPIS,30.0,TAGTATTAC,138.5,CVM_iter1_V_A,MEQAHGTGTPGNTIARCSKRRAYIITFWIKDYPKELPSKTKYLATC...
142,2517212,Porcine serum associated circular DNA virus 2,"(57, 65)",KAHIEICRG,30.5,TAATAATAC,133.4,CVM_iter1_V_A,MRLKNNEELKNDLIALKTCDYLLSCEEEAPTTKHKHIHIYVHFSQP...
143,1843770,Duck faeces associated circular DNA virus 3,"(89, 97)",RPNLEKVQS,21.6,AACTATTAC,136.1,CVM_iter1_V_A,MEHHQQIIQTPAIYEFRGVRALITYPQCNDGNKEELLTFLKTIYNN...
144,2766568,Giardia-associated CRESS DNA virus 4,"(72, 80)",RAHWEQARG,37.6,TAGTATTAC,138.5,CVM_iter1_V_A,MAATAWCGTLHLDTEEFDGETFLKQLVEAKRIAYGIGQIERCPTTG...
145,3133161,Ruminococcoides intestinihominis,"(75, 83)",VAHIDKANG,36.3,CATTACTAC,135.4,CVM_iter1_V_A,MGSANPQSRKWILTINNPEKYELNHESVKDILHLFNPDYFCLVDEI...
146,2169856,Mouse associated cyclovirus 1,"(75, 83)",GSHIEQAKG,38.9,TAATACTAC,134.9,CVM_iter1_V_A,MDSHVRRARWCFTTNNYTDDDIYRLRTLGNAISTNGYLLFGYEIAP...
148,10834,Wheat dwarf virus,"(91, 99)",HPNIQAAKD,42.7,TAATCCGAC,130.2,WDV_iter1_V_R,MASSSAPRFRVYSKYLFLTYPQCTLEPQYALDSLRTLLNKYEPLYI...
149,2012856,Rice latent virus 1,"(85, 93)",HPNCQPAQN,34.6,TAATGTTAC,137.6,WDV_iter1_V_R,MADPSTSHQFSVRTKYFFLTYPKCPVDPWELLHYLLTLLHSRVPIY...
150,1302848,Chickpea chlorosis Australia virus,"(86, 94)",HPNIQPAKN,36.6,TAATGTTAC,137.6,WDV_iter1_V_R,MPQTKKPSSSFRLQTKYVFLTYPRCSSDAESLRDFLWEKLSRFAIF...
151,1249648,Dragonfly-associated mastrevirus,"(88, 96)",HPNIQSAIS,35.6,TAATGTTAC,137.6,WDV_iter1_V_R,MSSSSAQSGPSHFRIRAQNIFLTYPRCDLDPKDAGEIIQSKMQSHE...
152,603333,Sweet potato symptomless virus 1,"(86, 94)",HPNIQPARD,36.5,TAATACGAC,132.0,WDV_iter1_V_R,MPRQPRARSVFSFSSKYGFLTYSQCDLTAEIIQQMLITLLTPFNLL...
153,1476487,Axonopus compressus streak virus,"(87, 95)",HPNIQSARS,38.1,TAATATTAC,139.3,WDV_iter1_V_R,MNNTEHGGPSGFRFQSRNIFLTYPRCNLAPELIGSFLLSLLSPYHV...
154,1182518,Maize streak Reunion virus,"(125, 133)",HPNIQASRS,34.4,TAATATTAC,139.3,WDV_iter1_V_R,MSAFGNHFVPTPSVQAEVPTPLPGSDYPSEEDDLLQHDTPVGPDPP...