In [10]:
import torch
import pandas as pd

In [11]:
df = pd.read_csv("../oritdb_pairs.csv")

In [12]:
df

,oriTDB_accession,oriTDB_id,nic site,relaxase_family,relaxase_sequence,host
0,100001,GAATAAGGGACAGTGAAGAAGGAACACCCGCTCGCGGGTGGGCCTA...,60..61,TraI,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...,Pseudomonas aeruginosa
1,100002,CCGGCCAGCCTCGCAGAGCAGGATTCCCGTTGAGCACCGCCAGGTG...,107..108,TraI,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...,Klebsiella aerogenes K8841
2,100003,CCAGTTTCTCGAAGAGAAACCGGTAAGTGCGCCCTCCC,31..32,MobA,MAIYHLTAKTGSRSGGQSARAKADYIQREGKYARDMDEVLHAESGH...,Escherichia coli
3,100004,TTGCCCTATCCTGCATCGC,13..14,TaxC,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...,E. coli
4,100005,TTGCCCTATCCTGCATCGC,13..14,TaxC,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...,E. coli
...,...,...,...,...,...,...
668,100669,TCACTTCAGGCTCCTTACGGGGTGTCGGGGCGAAGCCCTGACCAGA...,96..97,NikB,MNAVIPKKRRDGKSSFEDLVSYVSVRDDMTDEELDLSSSSQAEQPH...,Escherichia coli strain C9
669,100670,TCACTTCAGGCTCCTTACGGGGTGTCGGGGCGAAGCCCTGACCAGA...,96..97,Relaxase,MNAVIPKKRRDGKSSFEDLVSYVSVRDDMTDEELDLSSSSQAEQPH...,Escherichia coli strain D3
670,100671,CGCACCGCTAGCAGCGCCCCTAGCGGTATCCTATAAAAAAACACAC...,251..252,TraI,MMSIAQVRSAGSAGNYYTDKDNYYVLGSMGERWAGRGAEQLGLQGS...,Escherichia coli strain D6
671,100672,CGCACCGCTAGCAGCGCCCCTAGCGGTATCCTATAAAAAAACACAC...,251..252,TraI,MMSIAQVRSAGSAGNYYTDKDNYYVLGSMGERWAGRGAEQLGLQGS...,Escherichia coli strain D10
672,100673,GGGTGTCGGGGCGCAGCCATGACCCAGTCACGTAGCGATAGCGGAG...,56..57,NaN,MIVKFHARGKGGGSGPVDYLLGRERSREGARVLRGAPEEVRELIDA...,Escherichia coli strain D10

In [13]:

filtered_df = df.copy()

filtered_df = filtered_df[filtered_df["relaxase_sequence"].notna() & (df["nic site"] != '_')]
filtered_df = filtered_df[filtered_df["oriTDB_id"].notna()]

In [15]:
print(len(filtered_df))
filtered_df

518

,oriTDB_accession,oriTDB_id,nic site,relaxase_family,relaxase_sequence,host
0,100001,GAATAAGGGACAGTGAAGAAGGAACACCCGCTCGCGGGTGGGCCTA...,60..61,TraI,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...,Pseudomonas aeruginosa
1,100002,CCGGCCAGCCTCGCAGAGCAGGATTCCCGTTGAGCACCGCCAGGTG...,107..108,TraI,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...,Klebsiella aerogenes K8841
2,100003,CCAGTTTCTCGAAGAGAAACCGGTAAGTGCGCCCTCCC,31..32,MobA,MAIYHLTAKTGSRSGGQSARAKADYIQREGKYARDMDEVLHAESGH...,Escherichia coli
3,100004,TTGCCCTATCCTGCATCGC,13..14,TaxC,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...,E. coli
4,100005,TTGCCCTATCCTGCATCGC,13..14,TaxC,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...,E. coli
...,...,...,...,...,...,...
668,100669,TCACTTCAGGCTCCTTACGGGGTGTCGGGGCGAAGCCCTGACCAGA...,96..97,NikB,MNAVIPKKRRDGKSSFEDLVSYVSVRDDMTDEELDLSSSSQAEQPH...,Escherichia coli strain C9
669,100670,TCACTTCAGGCTCCTTACGGGGTGTCGGGGCGAAGCCCTGACCAGA...,96..97,Relaxase,MNAVIPKKRRDGKSSFEDLVSYVSVRDDMTDEELDLSSSSQAEQPH...,Escherichia coli strain D3
670,100671,CGCACCGCTAGCAGCGCCCCTAGCGGTATCCTATAAAAAAACACAC...,251..252,TraI,MMSIAQVRSAGSAGNYYTDKDNYYVLGSMGERWAGRGAEQLGLQGS...,Escherichia coli strain D6
671,100672,CGCACCGCTAGCAGCGCCCCTAGCGGTATCCTATAAAAAAACACAC...,251..252,TraI,MMSIAQVRSAGSAGNYYTDKDNYYVLGSMGERWAGRGAEQLGLQGS...,Escherichia coli strain D10
672,100673,GGGTGTCGGGGCGCAGCCATGACCCAGTCACGTAGCGATAGCGGAG...,56..57,NaN,MIVKFHARGKGGGSGPVDYLLGRERSREGARVLRGAPEEVRELIDA...,Escherichia coli strain D10

In [6]:
df['relaxase_length'] = df['relaxase_sequence'].str.len()

df

,oriTDB_accession,oriTDB_id,nic site,relaxase_family,relaxase_sequence,host,relaxase_length
0,100001,GAATAAGGGACAGTGAAGAAGGAACACCCGCTCGCGGGTGGGCCTA...,60..61,TraI,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...,Pseudomonas aeruginosa,732.0
1,100002,CCGGCCAGCCTCGCAGAGCAGGATTCCCGTTGAGCACCGCCAGGTG...,107..108,TraI,MIAKHVPMRSIKKSDFAELVKYITDEQGKTERLGHVRVTNCEANTL...,Klebsiella aerogenes K8841,732.0
2,100003,CCAGTTTCTCGAAGAGAAACCGGTAAGTGCGCCCTCCC,31..32,MobA,MAIYHLTAKTGSRSGGQSARAKADYIQREGKYARDMDEVLHAESGH...,Escherichia coli,700.0
3,100004,TTGCCCTATCCTGCATCGC,13..14,TaxC,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...,E. coli,385.0
4,100005,TTGCCCTATCCTGCATCGC,13..14,TaxC,MGVFVEKDYRVKRKSSENGRKSAFAHKVKNGGENYKKNVREKINRK...,E. coli,385.0
...,...,...,...,...,...,...,...
566,100567,AGCGCCGCAGATAATCTGACCGATTACCTCCTGAAACCAGGTCTAT...,301..302,NaN,MLDITTITRQNVTSVVGYYSDAKDDYYSKDSSFTSWQGTGAEALGL...,Escherichia coli,1080.0
567,100568,AGCGCCGCAGATAATCTGACCGATTACCTCCTGAAACCAGGTCTAT...,301..302,NaN,MLDITTITRQNVTSVVGYYSDAKDDYYSKDSSFTSWQGTGAEALGL...,Escherichia coli,1080.0
568,100569,TCACTTCAGGCTCCTTACGGGGTGTCGGGGCGAAGCCCTGACCAGA...,96..97,NikB,MTDEELNLSSSSQAEQPHRSRFSRLVDYATRLRNESFVALVDVMKD...,Escherichia coli,871.0
569,100570,CGCACCGCTAGCAGCGCCCCTAGCGGTATCCTATAAAAAAACACAC...,251..252,TraI,MLTGNLVMALFNHDTSRDQEPQLHTHAVVANVTQHNGEWKTLSSDK...,Escherichia coli,1623.0
570,100571,AGCGCCGCAGATAATCTGACCGATTACCTCCTGAAACCAGGTCTAT...,301..302,TraI,MLDITTITRQNVTSVVGYYSDAKDDYYSKDSSFTSWQGTGAEALGL...,Escherichia coli,1078.0

In [9]:
from IPython.display import display, HTML

# Wrap df.to_html() in a scrollable div using IPython display
with pd.option_context('display.max_rows', None):
    display(HTML("<div style='height: 300px; width: 100%; overflow: auto;'>" + filtered_df.to_html() + "</div>"))